import type { Metadata } from "next";
import { Oswald, Geist_Mono, Manrope } from "next/font/google";
import "@/styles/globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import NotificationsProvider from "@/components/providers/NotificationsProvider";
import { ToastProvider } from "@/components/ui/Notification";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${oswald.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
      >
        <NotificationsProvider>
          <Header />
          {children}
          <Footer />
          <ToastProvider />
        </NotificationsProvider>
      </body>
    </html>
  );
}
